# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
source "/home/techknowfile/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.plugin.zsh"
source "/home/techknowfile/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/home/techknowfile/.zgen/bhilburn/powerlevel9k-master/powerlevel9k.zsh-theme"

# ### Plugins & Completions
fpath=(/home/techknowfile/.zgen/zsh-users/zsh-history-substring-search-master /home/techknowfile/.zgen/zsh-users/zsh-syntax-highlighting-master /home/techknowfile/.zgen/bhilburn/powerlevel9k-master ${fpath})

autoload -Uz compinit && \
   compinit -C 

# }}}
