# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
source "/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/oh-my-zsh.sh"
source "/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh"
source "/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/heroku/heroku.plugin.zsh"
source "/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/pip/pip.plugin.zsh"
source "/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh"
source "/home/techknowfile/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.plugin.zsh"
source "/home/techknowfile/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/home/techknowfile/.zgen/bhilburn/powerlevel9k-master/powerlevel9k.zsh-theme"

# ### Plugins & Completions
fpath=(/home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master /home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/git /home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/heroku /home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/pip /home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/lein /home/techknowfile/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found /home/techknowfile/.zgen/zsh-users/zsh-history-substring-search-master /home/techknowfile/.zgen/zsh-users/zsh-syntax-highlighting-master /home/techknowfile/.zgen/bhilburn/powerlevel9k-master ${fpath})

autoload -Uz compinit && \
   compinit -C 

# }}}
